[runner]
magicEnabled = false
fastReruns = true

[theme]
primaryColor="#213ab3"
backgroundColor="#eaecd3"
secondaryBackgroundColor="#efd576"
textColor="#1a528e"
font = "Indie Flower:https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap, sans-serif"
baseFontSize = 17